concurrent = 1
check_interval = 0
log_level = "warning"
log_format = "text"

[session_server]
  listen_address = "[::]:8093"
  session_timeout = 1800

[[runners]]
  name = "web-dev"
  url = "https://gitlab.com/"
  token = "oybE6gA26K1RG1GeMecr"
  builds_dir = "/root/builds"
  executor = "ssh"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.ssh]
    user = "root"
    password = "apppassword"
    host = "188.166.214.118"
    port = "22"
    identity_file = "/root/.ssh/id_rsa"
