variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR

cache:
    key:
      files:      
         - package.json
    paths:
      - dist 

stages:
    - build
    - test  
    - archive
    - deploy     

build:
    stage: build
    environment:
        name: development
        url: http://188.166.214.118/development
    tags:
        - s1
    artifacts: 
      public: true
      when: on_success     
      paths:
        - dist/
    before_script:   
        - pwd && cd $CI_BUILDS_DIR        
        - npm ci --cache .npm --prefer-offline
        - ansible-playbook -i hosts playbook/playbook.yml --syntax-check
        - ansible-playbook -i hosts playbook/playbook.yml 

    rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      - if: '$CI_COMMIT_BRANCH == "master"'
        when: on_success          
        allow_failure: true
      - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        when: always
      - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/'
        when: manual
        allow_failure: true
      - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'      
      - if: '$CI_COMMIT_TAG != ""'       

    script: 
        - pwd && cd $CI_BUILDS_DIR     
        - ./node_modules/@angular/cli/bin/ng build --prod --base-href /development/     

    retry:
      max: 2
      when: always
    allow_failure: true        
    after_script:                 
        - echo "Build development complete"    

test:
    stage: test
    environment:
        name: development
        url: http://188.166.214.118/development
    tags:
        - s1
    script:
        - echo "Skipping..." #npm run test
        - echo "Skipping..." #npm run lint
        - echo "Skipping..." #npm run e2e

    only:
        - master

    allow_failure: true

    retry:
      max: 2
      when: 
       - runner_system_failure
       - stuck_or_timeout_failure
    allow_failure: true
    when: delayed
    start_in: 1 minutes
    after_script:
        - echo "Test development complete..."

archive:
    stage: archive
    environment:
        name: development
        url: http://188.166.214.118/development
    tags:
        - s1    
    before_script:
        - echo "Skipping..." #npm publish  
        - ls -ltr $DIR_RELEASE          
      
    script:
        - | 
          if [ -d $DIR_RELEASE ]; then 
            echo "Directory Is exists."; 
          else 
            mkdir -p $DIR_RELEASE/web_app;
            echo "Create Directory Success...";
          fi
        - | 
          if [ -f "*.zip" ]; then 
            echo "This package already downloaded..."; 
            unzip *.zip -d $DIR_RELEASE/web_app/; 
          else 
            echo "Preparing Archive package...";
            cd $CI_BUILDS_DIR && pwd
            zip -r development.zip dist/material-app && cp -r development.zip $DIR_RELEASE/web_app/            
            echo "Archiving Package success...!";
          fi   
    only:
        - master    

    retry:
      max: 2
      when: always         
    allow_failure: true
    when: delayed
    start_in: 1 minutes
    after_script:
        - echo "Archive development complete..."

deploy:
    stage: deploy
    environment:
        name: development
        url: http://188.166.214.118/development
    tags:
        - s1
    before_script:
        - echo "backup dir web server"
        - cd /var/www/html 
        - | 
          if [ -e "development_`date +%y_%m_%d`.tar.gz" ]; then 
            echo "Yes, file exists"; 
          else 
            echo "Compres Proses..."; 
            tar -cf development_`date +%y_%m_%d`.tar.gz development; 
            echo "compres success..."; 
          fi
        - tar -cf /var/www/html/development_`date +%y_%m_%d`.tar.gz /var/www/html/development
        
    script: 
        - cd $DIR_RELEASE/web_app && pwd
        - echo "Extract Package...."
        - unzip development.zip 
        - echo "deploy Success.."
        #- echo "Preparing remove packages web..."
        #- rm -rf /var/www/html/development 
        #- ls -ltr /var/www/html 
        #- echo "Remove Package Success..."
        #- mv dist/material-app /var/www/html/development
        #- echo "Make Sure Privileges user.."
        #- ls -ltr /var/www/html/development
        #- chown -Rv appuser01:www-data /var/www/html/development && chmod -Rv 755 /var/www/html/development
    only:
        - master

    retry:
      max: 2
      when: always      

    allow_failure: true
    when: delayed
    start_in: 1 minutes
    after_script:
        - echo "Deploy development complete..."
    



    


