before_script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    
variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/web_app
  npm_cache: /cache/npm-cache/

stages:
    - build   

build_development:
    stage: build   
    before_script:        
        - npm ci --cache .npm --prefer-offline
                
    script:
        - npm install   
        - ./node_modules/@angular/cli/bin/ng build --progress false --prod        
    cache:    
      paths:
        - node_modules/
    artifacts:
      expire_in: 2h30min
      paths:
        - dist/
    after_script:
        - echo "Build development complete"
        - cd ..
        - unset cd
    


